services:
  2hol:
    build:
      dockerfile: docker/2hol/Dockerfile
    image: ghcr.io/connorhsm/2hol-server:latest
    container_name: 2hol-server
    tty: true
    ports:
      - "8006:8006"
    volumes:
      - "./2hol-data:/usr/OneLife/server/data"
